---
dist: trusty
sudo: required
language: python

before_install:
  - sudo apt-get update

env:
  global:
    - ROLE_NAME: aviconfig
  matrix:
    - MOLECULE_DISTRO: centos:7
      MOLECULE_SERVICE_MANAGER: systemd
      MOLECULE_COMMAND: /usr/sbin/init
    - MOLECULE_DISTRO: ubuntu:16.04
      MOLECULE_SERVICE_MANAGER: systemd
      MOLECULE_COMMAND: /usr/sbin/init
    - MOLECULE_DISTRO: ubuntu:18.04
      MOLECULE_SERVICE_MANAGER: systemd
      MOLECULE_COMMAND: /usr/sbin/init
services:
  - docker

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME avinetworks.$ROLE_NAME
  - cd avinetworks.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    recipients:
#      - grastogi@avinetworks.com
#      - chaitanya.deshpande@avinetworks.com
#      - shrikant.patil@avinetworks.com
      - rohan.suryawanshi@avinetworks.com
    on_failure: always
