---
dist: bionic
language: python
python:
  - "3.7"

before_install:
  - sudo apt-get update

env:
  global:
    - ROLE_NAME: aviconfig
  matrix:
    - MOLECULE_DISTRO: ubuntu:16.04
services:
  - docker

install:
  - pip install molecule docker pluggy==0.13.1 yamllint ansible-lint docker molecule-docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME avinetworks.$ROLE_NAME
  - cd avinetworks.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    recipients:
      #- rastogiga@vmware.com
      #- deshpandech@vmware.com
      #- pshrikan@vmware.com
      #- sabandi@vmware.com
      #- shounakj@vmware.com
    on_failure: always
