FROM ubuntu:14.04
RUN apt-get update

# Install Ansible
RUN apt-get install -y software-properties-common git
RUN apt-get install -y python-pip
RUN apt-add-repository -y ppa:ansible/ansible
RUN add-apt-repository -y ppa:jonathonf/python-2.7
RUN apt-get update
RUN apt-get install -y ansible
RUN apt-get install -y python2.7
RUN pip install avisdk

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
